export const LOGIN_WITH_OTP_THROTTLE_TTL = 5000;
export const LOGIN_WITH_OTP_THROTTLE_LIMIT = 1;
export const GENERATE_OTP_THROTTLE_TTL = 5000;
export const GENERATE_OTP_THROTTLE_LIMIT = 1;
export const PEERTUBE_LOGIN_API_THROTTLE_TTL = 10000;
export const PEERTUBE_LOGIN_API_THROTTLE_LIMIT = 15;
export const UPDATE_NOMINATION_STATUS =
  "Casttree.Events.Update.Nomination.Status";
